/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    KAsyncButton: typeof import('./components/async/k-async-button.vue')['default']
    KCheckbox: typeof import('./components/form/k-checkbox.vue')['default']
    KDatePicker: typeof import('./components/form/k-date-picker.vue')['default']
    KFormItem: typeof import('./components/form/k-form-item.vue')['default']
    KInput: typeof import('./components/form/k-input.vue')['default']
    KInputNumber: typeof import('./components/form/k-input-number.vue')['default']
    KRadio: typeof import('./components/form/k-radio.vue')['default']
    KSelect: typeof import('./components/form/k-select.vue')['default']
    KSwitch: typeof import('./components/form/k-switch.vue')['default']
    KTableDate: typeof import('./components/table/k-table-date.vue')['default']
    KTableDict: typeof import('./components/table/k-table-dict.vue')['default']
    KTableOperations: typeof import('./components/table/k-table-operations.vue')['default']
    KTreeSelect: typeof import('./components/form/k-tree-select.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
